In [41]:
import itertools
import pandas as pd
import numpy as np
import random
import csv
import time

import matplotlib.pyplot as plt
import os
import tensorflow as tf
# from data_util import read_file
import random

In [42]:
tf.test.is_gpu_available()

False

In [38]:
import ast  

def read_file(filename):
    df = pd.read_csv(filename)
    state = [ast.literal_eval(i) for i in df['state'].values.tolist()]
    user = df['user'].values.tolist()
    history = [ast.literal_eval(i) for i in df['history'].values.tolist()]
    
    data = pd.DataFrame ()
    data['user'] = user
    data['state'] = state
    data['history'] = history
    return data

In [3]:
data = read_file('./data/ml-100k/train_data.csv')

In [43]:
len(data)

943

In [45]:
data.loc[942]

user                                                     940
state                              [257, 299, 293, 357, 407]
history    [116, 918, 180, 297, 256, 6, 762, 992, 123, 47...
Name: 942, dtype: object

In [4]:
from embeddings import Embeddings
item_embeddings = Embeddings(np.load('./data/ml-100k/item_embed.npy'))
user_embeddings = Embeddings(np.load('./data/ml-100k/user_embed.npy'))

In [40]:
from environment import Environment
env = Environment(data, item_embeddings, user_embeddings, 0.9).reset(10)

In [ ]:
random 

In [20]:
state = env.current_state
state.shape[0]

5

In [11]:
embeds = item_embeddings.get_embedding_vector()

In [32]:
scores = tf.linalg.matmul(state, tf.transpose(embeds))

In [33]:
with tf.Session() as sess:
     sess.run(scores) #exe

In [36]:
a = np.array([[1,2,3],[3,4,5]])
a.reshape(-1)

array([1, 2, 3, 3, 4, 5])

In [6]:
actions = [[0.06300897844172536,
  0.10120325060147602,
  -0.07067135036012125,
  -0.032311522304845186,
  0.04158774924751493,
  0.04770557068972703,
  -0.05524537747502321,
  0.09619148967484595],
  [-0.32940129849660793,
  0.3784379357687106,
  0.22846474266313643,
  0.3872408961323892,
  0.5016216053094931,
  -0.35322230732586596,
  -0.18604901157054946,
  -0.32414148651485614],
          [0.18622014881368984,
  -0.013660540437454361,
  -0.13745905167151162,
  0.4602213581009562,
  0.5470134701293478,
  -0.002449350701645488,
  0.2621172847191586,
  0.2466560373311872],
          [0.21557977549194451,
  0.5515019944635859,
  -0.15300502349288145,
  0.5331932442032238,
  0.17151941158607348,
  0.32188020803217054,
  -0.26827991450515787,
  -0.33527392591872157]]

In [10]:
env.current_history

array([[ 0.20184646,  0.56169861,  0.14647907,  0.34874683,  0.38709448,
        -0.11442304,  0.32641887,  0.35552894],
       [ 0.25540843,  0.25332423,  0.26294983,  0.57263104,  0.31351944,
         0.0922362 ,  0.36785419, -0.07507234],
       [-0.38899094,  0.49690356,  0.44087976,  0.85893088, -0.22115704,
         0.18239039, -0.14394051,  0.16330508],
       [ 0.29668381,  0.08524114,  0.37237725,  0.70457379, -0.4915713 ,
        -0.65535941, -0.49692345, -0.21361112],
       [ 0.83604909, -0.4705504 , -0.30975711,  0.24216111,  0.63861993,
         0.21490916,  0.76525296,  0.48044442],
       [ 0.19625726,  0.73610656,  0.20763004,  0.23748853,  0.05018958,
         0.221497  , -0.32741095,  0.10578934],
       [ 0.01459349,  0.40069033, -0.28270592,  0.23803513,  0.69259573,
        -0.36236824, -0.01119533, -0.24605078],
       [ 0.2796569 , -0.29005929,  0.17462966,  0.41654598,  0.25547337,
        -0.06374545, -0.3603368 , -0.03042745],
       [ 0.05105   ,  0.11434958

In [13]:
test_action = [ 0.20184646]

In [14]:
test_action in env.current_history

False

In [9]:
[i in env.current_history for i in actions]

[False, False, False, False]

In [5]:
embedded_data = pd.DataFrame()
embedded_data['user'] = [np.array(user_embeddings.get_embedding (row['user'])) for _, row in data.iterrows ()]
embedded_data['state'] = [np.array(item_embeddings.embed(row['state'])) for _, row in data.iterrows ()]
embedded_data['history'] = [np.array(item_embeddings.embed(row['history'])) for _, row in data.iterrows ()]

In [10]:
np.array(user_embeddings.get_embedding (row['user'])), np.array(item_embeddings.embed(row['state'])) for _, row in data.iterrows ()

SyntaxError: invalid syntax (<ipython-input-10-fa5cc060853c>, line 1)

In [2]:
item_embed = np.load(os.path.dirname(os.getcwd())+'/data/ml-100k/item_embed.npy')

In [3]:
item_embed.shape

(1683, 8)

In [4]:
class Embeddings:
    def __init__(self, item_embeddings):
        self.item_embeddings = item_embeddings

    def size(self):
        return self.item_embeddings.shape[1]

    def get_embedding_vector(self):
        return self.item_embeddings

    def get_embedding(self, item_index):
        return self.item_embeddings[item_index]

    def embed(self, item_list):
        return np.array ([self.get_embedding (item) for item in item_list])

In [7]:
item_embeddings = Embeddings(item_embed)

In [8]:
item_embeddings.embed([1,5,10])

array([[-0.3294013 ,  0.37843794,  0.22846474,  0.3872409 ,  0.50162161,
        -0.35322231, -0.18604901, -0.32414149],
       [ 0.16243079,  0.15634468,  0.01543459,  0.2316866 ,  0.66710608,
        -0.18403334,  0.67564983, -0.06392998],
       [-0.04695697, -0.1019572 , -0.07385104,  0.61410682, -0.2923867 ,
         0.03815775, -0.17699849, -0.27747634]])

In [11]:
item_embed[0][1:]

array([ 0.10120325, -0.07067135, -0.03231152,  0.04158775,  0.04770557,
       -0.05524538,  0.09619149])

In [12]:
u = [item_embed[0][0],item_embed[0][6:]]
u

[0.06300897844172536, array([-0.05524538,  0.09619149])]

ModuleNotFoundError: No module named 'data_util'